//@version=3
// Copyright (c) 2018-present, Michael Deng (mdeng1024)
// Least Squares Moving Average based strategy
study("Adaptive Least Squares Moving Average", shorttitle="Adaptive LSR MA", overlay=false)

src=input(hl2, title="Source") 
a=input(.07, title="Alpha")
sign = input(false, title="Show Trade Signal")

ip = 0.0
p = 0.0

// smooth price data
s = (src + 2*src[1] + 2*src[2] + src[3])/6.0

// prepare cycle
c = s[0]
c := n<7 ? (src - 2*src[1] + src[2])/4.0 : ((1 - 0.5*a)*(1 - 0.5*a)*(s - 2*s[1] + s[2]) + 2*(1-a)* nz(c[1]) - (1 - a)*(1-a)* nz(c[2]))

// 
q1 = (.0962*c + 0.5769*c[2] - 0.5769*c[4] - .0962*c[6])*(0.5+.08*nz(ip[1]))
I1 = c[3]
dp_ = iff(q1 != 0 and q1[1] != 0, (I1/q1 - I1[1]/q1[1]) / (1 + I1*I1[1]/(q1*q1[1])),0.0)
dp = iff(dp_ < 0.1, 0.1, iff(dp_ > 0.9, 0.9, dp_))

med(x,y,z) => (x+y+z) - min(x,min(y,z)) - max(x,max(y,z))
md = med(dp,dp[1], med(dp[2], dp[3], dp[4]))

dc = iff(md == 0, 15, 6.28318 / md + 0.5)
ip := .33*dc + .67*nz(ip[1])
p := .15*ip + .85*nz(p[1])

length = 0
length := p > 50? 50: (p < 10? 10: 0+round(p)[0])
plot(length)
// src1 = close
// src2 = hl2

// https://www.mathsisfun.com/data/least-squares-regression.html
lsrma(src, leng) => 
    len = leng + 0
    if n <= len
        src
    else 
        xys = 0.0
        xs = 0.0
        ys = 0.0
        x2s = 0.0
        for i = 0 to len-1
            x = n-i
            y = src[i]
            xys := xys + x * y
            xs := xs + x
            ys := ys + y
            x2s := x2s + x * x
        b = (len * xys - xs * ys) / (len * x2s - xs * xs)
        a = (ys - b * xs) / len
        a + b * n

clr = lsrma(src, length)
// plot(clr, title="lsma-close", linewidth=1, color=blue, transp=0)
// hl2lr = linreg(src1, length, 0)
// plot(hl2lr, title="lsma", linewidth=1, color=blue, transp=0)

// PI = 3.14159
// smooth(src, len) =>
// 	arg = 1.414 * PI / len
// 	a1 = exp(-arg)
// 	b1 = 2 * a1 * cos(arg)
// 	c2 = b1
// 	c3 = -a1 * a1
// 	c1 = 1 - c2 - c3

// 	filt = 0.0
// 	filt := c1 * (src + nz(src[1])) / 2 + c2 * nz(filt[1]) + c3 * nz(filt[2])

// smoothClr = smooth(clr, length/2)
// smoothHl2lr = smooth(hl2lr, length/2)

// plot the LSQ MAs
// plot(smoothClr, title="lsma-close", linewidth=1, color=blue, transp=0)
// plot(smoothHl2lr, title="lsma-hl2", linewidth=1, color=red, transp=0)

// plot reference SMA
// plot(sma(src1, 50), color=red, linewidth=2, title="SMA50")

// plot range band (fixed Bollinger)
// ma = sma(src1, 20)
// dev = stdev(src1, 20)
// up = ma + 2 * dev
// dn = ma - 2 * dev
// upPlot = plot(up, color=#128484, title="BBand-Up")
// lowPlot = plot(dn, color=#128484, title="BBand-Low")
// fill(upPlot, lowPlot, color=#128484, transp=95)

// plot buy/sell signal
// peaks = sign? crossunder(smoothClr, smoothHl2lr): false
// valleys = sign? crossover(smoothClr, smoothHl2lr) : false
        
// plotshape(peaks? up + 0.2 * dev : na, color=red, style=shape.arrowdown, size=size.auto, location=location.absolute, text="Sell")
// plotshape(valleys? dn - 0.2 * dev : na, color=green, style=shape.arrowup, size=size.auto, location=location.absolute, text="Buy")
