//@version=3
// sample included in TradingView
strategy("Bollinger Bands Strategy", overlay=true)

source = close
length = input(20, minval=1)
mult = input(2.0, minval=0.001, maxval=50)

basis = sma(source, length)
dev = mult * stdev(source, length)

upper = basis + dev
lower = basis - dev

// plot BBand for easy track the orders entry logic
upPlot = plot(upper, color=#128484, title="BBand-Up")
lowPlot = plot(lower, color=#128484, title="BBand-Low")
fill(upPlot, lowPlot, color=#128484, transp=95)


// trade logic
buyEntry = crossover(source, lower)
sellEntry = crossunder(source, upper)

if (buyEntry)
    strategy.entry("BBandLE", strategy.long, stop=lower, oca_name="BollingerBands", oca_type=strategy.oca.cancel, comment="BBandLE")
else
    strategy.cancel(id="BBandLE")

if (sellEntry)
    strategy.entry("BBandSE", strategy.short, stop=upper, oca_name="BollingerBands", oca_type=strategy.oca.cancel, comment="BBandSE")
else
    strategy.cancel(id="BBandSE")


//plot(strategy.equity, title="equity", color=red, linewidth=2, style=areabr)
