​//@version=3

// https://backtest-rookies.com/2017/08/07/tradingview-adding-quandl-data-sources/

strategy(title="Global Metal Inventories Strategy", overlay=true, default_qty_type=strategy.percent_of_equity,default_qty_value=10)

//Add an input for Metal Selection
metal = input(defval='CU', title='Metal', options=['AL','CU','ZI'])

// Create syms
stBase = 'QUANDL:LME/ST_'
stSym = stBase + metal + '_ALL'

//Get data
st = security(stSym,'D', close[0])

//Get data for current Chart
stHigh = security(ticker,'D', high[0])

stChange = ((st[0] - st[1]) / st[1]) * 100

shortConditionOne = stChange > 10
if (shortConditionOne)
    strategy.entry("Oversupply", strategy.short, stop=stHigh[0])
    
closeConditionOne = stChange <=0
if (closeConditionOne)
    strategy.close("Oversupply")